-- Root module for Von Neumann Regular Rings Generalizations Canonical Lane Lean
import VonNeumannRegularRingsGeneralizationsCanonicalLaneLean.MathlibObjects
import VonNeumannRegularRingsGeneralizationsCanonicalLaneLean.AdmissibleClass
import VonNeumannRegularRingsGeneralizationsCanonicalLaneLean.Projection
import VonNeumannRegularRingsGeneralizationsCanonicalLaneLean.BridgeLemmas
import VonNeumannRegularRingsGeneralizationsCanonicalLaneLean.GateLemmas
import VonNeumannRegularRingsGeneralizationsCanonicalLaneLean.FinalTheorem
import VonNeumannRegularRingsGeneralizationsCanonicalLaneLean.TheoremStatement

namespace HautevilleHouse
namespace VonNeumannRegularRingsGeneralizationsCanonicalLaneLean

-- Root module content

end VonNeumannRegularRingsGeneralizationsCanonicalLaneLean
end HautevilleHouse